apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
    #argocd.argoproj.io/hook: "0"
spec:
  parallelism: 4
  script:
    configMap:
      name: crocodile-stress-test
      file: new.js
