apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  parallelism: 2
  script:
    configMap:
      name: crocodile-stress-test
      file: new.js
  arguments: -o xk6-prometheus-rw
  runner:
    image: k6-prometheus:latest
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://172.21.43.203:9090/api/v1/write
